### ISSUE TITLE
AppleID is required again when dSYMs aren't being downloaded

### ISSUE THREAD

**Issue by kyanar** [Dynatrace/fastlane-plugin-dynatrace#15]
Commit 74a1c5b92fbe38d472cea8c03a74b49c57306e83 seems to have reintroduced a behaviour where an AppleID/username is always required for the upload_dynatrace_symbols action, even when the app is an enterprise/in-house app where dSYMs cannot be downloaded from App Store Connect.

Running the action without supplying a `username` parameter returns the below (redacted sensitive/internal info)

    DTXDssClientPath: /usr/local/bin/dynatrace/DTXDssClient
    Parameter API Token: ****
    OS: ios
    Version string: 4.74.7
    Version 8457
    Server URL: https://*****/e/********
    Checking AppFile for possible AppID
    BundleID: ****
    Checking AppFile for possible username/AppleID
    No value found for 'username'

**Comment by cynicer** [comment]
Thanks for reporting! The bug will be fixed with #16

**Comment by cynicer** [comment]
Fixed by 8bc0e07, will be included in the next release.
