### ISSUE TITLE
Error fetching symbols version: The data couldn’t be read because it isn’t in the correct format

### ISSUE THREAD

**Issue by Raphzz** [Dynatrace/fastlane-plugin-dynatrace#6]
Hi!
I am trying to implement Dynatrace on our fastlane runtime using the following code:
`
  download_dsyms(
    wait_for_dsym_processing: true,
	  wait_timeout: symbols_wait_timeout,
	  app_identifier: "com.ashworthandparker.end",
	  version: version, 
	  build_number: build
  )

  dynatrace_process_symbols(
	  symbolsfile: lane_context[SharedValues::DSYM_PATHS][0],
	  dtxDssClientPath: ENV["DTXDSSClIENT_PATH"],
	  appId: app_id,
	  apitoken: api_token,
	  os: "ios",
	  versionStr: build,
	  version: version,
	  server: server_url,
  )`

The lane that downloads the symbols are working fine, I can see the zip containing the dSYM file, but when I try to upload it, I get the error:
 "Execution failed, rc=-1 reason=Error fetching symbols version: The data couldn’t be read because it isn’t in the correct format"

When trying to upload it manually, I get the same error.
I hope I can get some help here.

Thanks!

**Comment by MANassar** [comment]
Hey @Raphzz, this error usually means you are using a DTXDssClient version that is incompatible with your cluster version. 

Please make sure that your cluster version and your DTXDssClient version are matching.

**Comment by MANassar** [comment]
Since this is not a fastlane related issue. I will close this issue. If the problem with the upload persists, please create a support ticket on [https://support.dynatrace.com](https://support.dynatrace.com)
