### ISSUE TITLE
dynatrace_process_symbols doesn't use value passed in 'bundleId'

### ISSUE THREAD

**Issue by kedio** [Dynatrace/fastlane-plugin-dynatrace#7]
When running the dynatrace_process_symbols as part of a fastlane script the value passed to `bundleId` is not passed to the DTXDssClient command

For example I call the function like this in the fastlane script:
```
    dynatrace_process_symbols(
        dtxDssClientPath: "./buildScripts/dynatrace/DTXDssClient",
        apitoken: "<apitoken>",
        os: "<os>",
        versionStr: lane_context[SharedValues::VERSION_NUMBER],
        version: lane_context[SharedValues::BUILD_NUMBER],
        bundleId: "<bundleId>",
        symbolsfile: lane_context[SharedValues::DSYM_OUTPUT_PATH],
        server: "<server>",
        appId: "<appId>",
        debugMode: true
    )
```

I can see `bundleId` being printed out with the rest of the arguments, but the DTXDssClient command have an empty `bundleId` value.

Looking quickly through the code in `lib/fastlane/plugin/dynatrace/actions/dynatrace_action.rb` it seems like `bundleId` is assigned only from the value in `appfile` but not from params as a fallback.

**Comment by MANassar** [comment]
Hello kedio,

Which version of the plugin are you using? Please update to the latest version 0.1.5 and let me know if you still see this behavior.

**Comment by kedio** [comment]
Hi MANassar,

I'm using version 0.1.5. I'm just starting to introduce this plugin in the pipeline.
